### ISSUE TITLE
Unable to get block data

### ISSUE THREAD

**Issue by cbrum11** [zkMIPS/cannon-mips#1]
I've done my best to follow instructions here... When using my payed HTTPS Alchemy key to query a block I get the following message...

Example:
minigeth/go-ethereum 13284469

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x686af7]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/oracle.(*Header).ToHeader(_)
	/home/chase/dev/cannon-mips/minigeth/oracle/apitypes.go:66 +0x77
github.com/ethereum/go-ethereum/oracle.PrefetchBlock(0xc00019f868, 0x1, {0x0, 0x0})
	/home/chase/dev/cannon-mips/minigeth/oracle/prefetch.go:273 +0x345
main.main()
	/home/chase/dev/cannon-mips/minigeth/main.go:58 +0x3b8

```
Any suggestions?

**Comment by cbrum11** [comment]
I'm not sure if it's helpful or a clue... but the first line of the error message (left out above) is the following... 

`override node url https://eth-mainnet.g.alchemy.com/v2/<my alchemy url>`

With the `my alchemy url` obviously being the string associated with my node.  I show this incase there's something obviously weird or wrong with the url format?

`

**Comment by cbrum11** [comment]
Ok... possibly getting somewhere.  When trying to curl my node with the following command, I get this error message.

Command:
`curl https://eth-mainnet.g.alchemy.com/v2/<my alchemy url> -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":73}'`

Error:
`
{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"IP address <IPV6 ip address> is not on whitelist."}}`

I've remove the IP address and URL string above.  Alchemy does not allow whitelisting of IPV6 addresses as far as I can tell - but my public IPV4 address is whitelisted in Alchemy (and has been this whole time).  Trying to figure out if there's a way to force the connection over IPV4

**Comment by cbrum11** [comment]
Ok... turns out curl has an `--ipv4` tag one can use.  Just ran again w/ tag and BOOM my manual curl command got a response when using the tag.  So my leading theory is that my computer is default using IPV6 when trying to make the go-ethereum query and Alchemy is blocking me.  Now how to force and ipv4 connection if not using curl... hmmmmm.

**Comment by cbrum11** [comment]
Hmmmm...

Have to force the client to use IPV4 in this line in the `oracle/prefetch.go` file, `getAPI()` function.

**Comment by cbrum11** [comment]
100% confirmed this is my issue... If uncomment the following lines in the `PrefetchBlock()` function I get the following error message...

`{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"IP address <my ipv6 address> is not on whitelist."}}`

Long way to get there... but I got there.  Now to figure out how to force IPV4 in go... oomph.

**Comment by cbrum11** [comment]
Welp...

I changed every instance of "tcp" to "tcp4" in the source code of the net package... `net/http/transport.go`

Probably the dumbest way ever to get this to work - but I've never use Golang in my life and wasn't able to get it to work any other way.  Closing - as this basically had nothing to do with cannon-mips. 

Someone else might find this useful - but I couldn't get the non source code editing ways to work: https://stackoverflow.com/questions/53055808/golang-force-net-http-client-to-use-ipv4-ipv6
